export enum enumLookupCodeGroup {
    TIPO_PAGO_PEAJE = "TIPO DE PAGO PEAJE",
    TIPO_DOC_IDENTIDAD = "TIPO DE DOC. IDENTIDAD",
    TIPO_EMPRESA = "TIPO DE EMPRESA",
    TIPO_SERVICIO = "TIPO DE SERVICIO",
    STATUS_SOLICITUD_SERVICIO = "STATUS SOLICITUD SERVICIO",
    STATUS_ORDEN_TRABAJO = "STATUS ORDEN DE TRABAJO",
    TIPO_COMBUSTIBLE = "TIPO DE COMBUSTIBLE",
    TAMANO_CONTENEDOR = "TAMAÑO DE CONTENEDOR",
    TIPO_MONEDA = "TIPO DE MONEDA",
    TIPO_LICENCIA = "TIPO DE LICENCIA"
}